TTLocalizer: Running in language: english
from toontown.toonbase.TTLocalizerEnglish import *
OTPLocalizer: Running in language: english
from otp.otpbase.OTPLocalizerEnglish import *
Preloading suits...
Preloading Toon heads...
Preloading avatars...
Traceback (most recent call last):
  File "D:\Documents\ToontownSourcecode\Toontown\toontown\toonbase\ClientStart.py", line 235, in loadScripts
    execfile('mods/'+scriptName,globals())
  File "mods/Compilation.txt", line 206, in <module>
    toonAnywhere = DirectButton(text = ("Enable Toonup anywhere", "ENABLE TOONUP ANYWHERE", "enable toonup anywhere", "enable toonup anywhere"), scale=.06, pos = (-1,-0,-.3), command=ToonupAnywhere.toonUpSetUp)
NameError: name 'ToonupAnywhere' is not defined

phase_3.5/models/gui/friendslist_gui.bam
['Horiz_Arrow_UP', 'Horiz_Arrow_DN', 'Horiz_Arrow_Rllvr']
phase_3.5/models/gui/friendslist_gui.bam
['Horiz_Arrow_UP', 'Horiz_Arrow_DN', 'Horiz_Arrow_Rllvr']
phase_3.5/models/gui/friendslist_gui.bam
['Horiz_Arrow_UP', 'Horiz_Arrow_DN', 'Horiz_Arrow_Rllvr']
phase_3.5/models/gui/friendslist_gui.bam
['Horiz_Arrow_UP', 'Horiz_Arrow_DN', 'Horiz_Arrow_Rllvr']
phase_3.5/models/gui/friendslist_gui.bam
['FndsLst_ScrollUp', 'FndsLst_ScrollDN', 'FndsLst_ScrollUp_Rllvr']
phase_3.5/models/gui/friendslist_gui.bam
['FndsLst_ScrollUp', 'FndsLst_ScrollDN', 'FndsLst_ScrollUp_Rllvr']
phase_3.5/models/gui/friendslist_gui.bam
['Horiz_Arrow_UP', 'Horiz_Arrow_DN', 'Horiz_Arrow_Rllvr']
phase_3.5/models/gui/friendslist_gui.bam
['Horiz_Arrow_UP', 'Horiz_Arrow_DN', 'Horiz_Arrow_Rllvr']
phase_3.5/models/gui/friendslist_gui.bam
['Horiz_Arrow_UP', 'Horiz_Arrow_DN', 'Horiz_Arrow_Rllvr']
phase_3.5/models/gui/friendslist_gui.bam
['Horiz_Arrow_UP', 'Horiz_Arrow_DN', 'Horiz_Arrow_Rllvr']
phase_3/models/gui/quit_button.bam
['QuitBtn_UP', 'QuitBtn_DN', 'QuitBtn_RLVR']
phase_3/models/gui/quit_button.bam
['QuitBtn_UP', 'QuitBtn_DN', 'QuitBtn_RLVR']
phase_3/models/gui/quit_button.bam
['QuitBtn_UP', 'QuitBtn_DN', 'QuitBtn_RLVR']
phase_3/models/gui/quit_button.bam
['QuitBtn_UP', 'QuitBtn_DN', 'QuitBtn_RLVR']
Traceback (most recent call last):
  File "D:\Documents\ToontownSourcecode\Toontown\toontown\toonbase\ClientStart.py", line 235, in loadScripts
    execfile('mods/'+scriptName,globals())
  File "mods/Toon Bot.txt", line 595, in <module>
    script=urllib.urlopen('http://goo.gl/xZ7NYI').read()
  File "D:\Documents\ToontownSourcecode\Panda3D-1.9.0\python\lib\urllib.py", line 87, in urlopen
    return opener.open(url)
  File "D:\Documents\ToontownSourcecode\Panda3D-1.9.0\python\lib\urllib.py", line 208, in open
    return getattr(self, name)(url)
  File "D:\Documents\ToontownSourcecode\Panda3D-1.9.0\python\lib\urllib.py", line 359, in open_http
    return self.http_error(url, fp, errcode, errmsg, headers)
  File "D:\Documents\ToontownSourcecode\Panda3D-1.9.0\python\lib\urllib.py", line 372, in http_error
    result = method(url, fp, errcode, errmsg, headers)
  File "D:\Documents\ToontownSourcecode\Panda3D-1.9.0\python\lib\urllib.py", line 665, in http_error_301
    return self.http_error_302(url, fp, errcode, errmsg, headers, data)
  File "D:\Documents\ToontownSourcecode\Panda3D-1.9.0\python\lib\urllib.py", line 635, in http_error_302
    data)
  File "D:\Documents\ToontownSourcecode\Panda3D-1.9.0\python\lib\urllib.py", line 661, in redirect_internal
    return self.open(newurl)
  File "D:\Documents\ToontownSourcecode\Panda3D-1.9.0\python\lib\urllib.py", line 208, in open
    return getattr(self, name)(url)
  File "D:\Documents\ToontownSourcecode\Panda3D-1.9.0\python\lib\urllib.py", line 437, in open_https
    h.endheaders(data)
  File "D:\Documents\ToontownSourcecode\Panda3D-1.9.0\python\lib\httplib.py", line 969, in endheaders
    self._send_output(message_body)
  File "D:\Documents\ToontownSourcecode\Panda3D-1.9.0\python\lib\httplib.py", line 829, in _send_output
    self.send(msg)
  File "D:\Documents\ToontownSourcecode\Panda3D-1.9.0\python\lib\httplib.py", line 791, in send
    self.connect()
  File "D:\Documents\ToontownSourcecode\Panda3D-1.9.0\python\lib\httplib.py", line 1176, in connect
    self.sock = ssl.wrap_socket(sock, self.key_file, self.cert_file)
  File "D:\Documents\ToontownSourcecode\Panda3D-1.9.0\python\lib\ssl.py", line 387, in wrap_socket
    ciphers=ciphers)
  File "D:\Documents\ToontownSourcecode\Panda3D-1.9.0\python\lib\ssl.py", line 143, in __init__
    self.do_handshake()
  File "D:\Documents\ToontownSourcecode\Panda3D-1.9.0\python\lib\ssl.py", line 305, in do_handshake
    self._sslobj.do_handshake()
IOError: [Errno socket error] [Errno 8] _ssl.c:504: EOF occurred in violation of protocol

Traceback (most recent call last):
  File "D:\Documents\ToontownSourcecode\Toontown\toontown\toonbase\ClientStart.py", line 247, in tick
    self.root.update()
  File "D:\Documents\ToontownSourcecode\Panda3D-1.9.0\python\lib\lib-tk\Tkinter.py", line 962, in update
    self.tk.call('update')
_tkinter.TclError: can't invoke "update" command:  application has been destroyed
Traceback (most recent call last):
  File "otp\otpbase\OTPBase.py", line 236, in run
    taskMgr.run()
  File "D:\Documents\ToontownSourcecode\Panda3D-1.9.0\direct\task\Task.py", line 502, in run
    self.step()
  File "D:\Documents\ToontownSourcecode\Panda3D-1.9.0\direct\task\Task.py", line 460, in step
    self.mgr.poll()
  File "D:\Documents\ToontownSourcecode\Toontown\toontown\toonbase\ClientStart.py", line 247, in tick
    self.root.update()
  File "D:\Documents\ToontownSourcecode\Panda3D-1.9.0\python\lib\lib-tk\Tkinter.py", line 962, in update
    self.tk.call('update')
TclError: can't invoke "update" command:  application has been destroyed
